"""mvau RTL emission: the thin shim around FINN's ``mvu_vvu_axi``.

Generalizes the cosim-validated ``temp_space/mvau-spike/mvau_bb.v``. One shim =
one MVU tile: it instantiates ``mvu_vvu_axi`` with the tile's folding parameters
and adapts the FINN AXIS interface to the Vitis-HLS RTL-blackbox contract:

  * active-high ``ap_rst``  ->  FINN's active-low ``ap_rst_n`` (inverted)
  * ``ap_ce`` global stall gating the three handshakes (safe on a fully
    backpressured module: no beat transfers when ce=0, dsp_zero injects bubbles)
  * ap_fifo ports the JSON binds (``*_dout/*_empty_n/*_read``, ``*_din/*_full_n/*_write``)
    -- AXIS ``TVALID/TREADY`` bind directly to ap_fifo ``empty_n/read`` & ``full_n/write``

The module name MUST equal the JSON ``c_function_name`` -- Vitis instantiates the
blackbox by the C function name, not ``rtl_top_module_name`` (learned in cosim).

Self-contained (only ``geometry`` as a sibling import).
"""

import geometry as _geom


def _tile(shape, tile=None, **plan_kwargs):
    """Return the per-instance MVU tile params for *shape*, computing the plan
    if a precomputed *tile* dict is not supplied."""
    if tile is not None:
        return tile
    return _geom.resolve_plan(shape, **plan_kwargs)["tile"]


def generate_shim(shape, module_name="mvau_core", force_behavioral=True,
                  tile=None, weights_in_core=False, init_file=None,
                  init_files=None, n_tiles=1, k_tiles=1, **plan_kwargs):
    """Emit the shim Verilog wrapping ``mvu_vvu_axi`` for one MVU tile.

    ``module_name`` must match the blackbox C function name. ``force_behavioral``
    bakes ``FORCE_BEHAVIORAL`` into the instance (1 for unisim-free cosim, 0 for
    real DSP primitives downstream).

    ``weights_in_core`` selects the weight-stationary shim: each of ``n_tiles``
    FINN ``memstream``s (init'd from ``init_files[i]``, one per N-column slice)
    bakes its weights and drives its tile's ``s_axis_weights`` internally -- no
    external weight FIFO port. With ``n_tiles>1`` the tiles are stitched in RTL:
    the activation FIFO fans out to all tiles and their outputs concatenate into
    one wide result beat (tile ``i`` occupies ``[i*PB +: PB]``). ``init_file`` is a
    single-tile shorthand for ``init_files=[init_file]``. The default (streamed)
    shim keeps the ``w_*`` port and is reserved for the two-operand case.
    """
    t = _tile(shape, tile=tile, **plan_kwargs)
    wbits = t["weight_stream_width_ba"]
    abits = t["input_stream_width_ba"]
    pbits = t["output_stream_width_ba"]
    fb = 1 if force_behavioral else 0
    n_tiles = int(n_tiles)
    k_tiles = int(k_tiles)
    m = int(shape[0])

    def _w(n):                            # bit-width to hold values 0..n-1
        return max(1, (n - 1).bit_length())
    if weights_in_core:
        if init_files is None:
            init_files = [init_file] if init_file else None
        if k_tiles > 1:
            return _generate_kt_shim(t, module_name, fb, wbits, abits, pbits,
                                     init_files, n_tiles, k_tiles, m)
        return _generate_ws_shim(t, module_name, fb, wbits, abits, pbits,
                                 init_files, n_tiles, m)
    if n_tiles != 1:
        raise NotImplementedError(
            "streamed (two-operand) shim does not support N-tiling yet; "
            "n_tiles>1 is implemented on the weight-stationary path")

    in_total = m * t['sf']     # activation beats/node (matches feed_a's m*SF reads)
    run_total = m * t['nf']    # output beats/node (matches requant's m*NF reads)
    return f"""// Generated by gemm-ip-gen (mvau target). Shim around FINN's mvu_vvu_axi.
// Tile: MW(K)={t['mw']} MH(N)={t['mh']} PE={t['pe']} SIMD={t['simd']} \
core={t['compute_core']} ACCU={t['accu_width']}
// Module name MUST equal the JSON c_function_name (Vitis instantiates by it).
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,     // active-high
    input  wire                 ap_ce,      // active-high clock enable / stall
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // weight FIFO (input)    {wbits} = ceil(PE*SIMD*WEIGHT_WIDTH/8)*8
    input  wire [{wbits - 1}:0] w_dout,
    input  wire                 w_empty_n,
    output wire                 w_read,
    // activation FIFO (input)  {abits} = ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{abits - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // output FIFO (output)     {pbits} = ceil(PE*ACCU_WIDTH/8)*8
    output wire [{pbits - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;

    // ---- ap_ctrl_chain invocation-level FSM: IDLE <-> RUN, one node/invocation ----
    localparam IDLE = 1'd0, RUN = 1'd1;
    reg                        state = IDLE;
    reg                        done_r = 0;
    reg  [{_w(in_total + 1) - 1}:0]  icnt = 0;   // activation beats accepted this node
    reg  [{_w(run_total + 1) - 1}:0]  ocnt = 0;   // output beats produced this node

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; icnt <= 0; ocnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= RUN; icnt <= 0; ocnt <= 0;
            end else if (state == RUN) begin
                if (in_tvalid & in_tready) icnt <= icnt + 1'b1;
                if (p_write) begin
                    if (ocnt == {run_total - 1}) begin
                        state <= IDLE; done_r <= 1'b1;
                    end else ocnt <= ocnt + 1'b1;
                end
            end
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

    wire         wgt_tvalid, wgt_tready;
    wire         in_tvalid,  in_tready;
    wire         out_tvalid, out_tready;
    wire [{pbits - 1}:0] out_tdata;

    // gate the activation handshake on icnt too: stop pulling A beats once this
    // node's {in_total} beats are accepted, even if the next node's rows are queued.
    wire in_open = (state == RUN) & (icnt != {in_total});

    // ce-gated ap_fifo <-> AXIS binding (empty_n==TVALID, read==TREADY,
    //                                    full_n==TREADY, write==TVALID)
    assign wgt_tvalid = ap_ce & w_empty_n;
    assign w_read     = ap_ce & wgt_tready;
    assign in_tvalid  = ap_ce & in_open & a_empty_n;
    assign a_read     = ap_ce & in_open & in_tready;
    assign out_tready = ap_ce & p_full_n;
    assign p_write    = ap_ce & out_tvalid & p_full_n;   // count only real transfers
    assign p_din      = out_tdata;

    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}),
        .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({t['mh']}), .PE({t['pe']}), .SIMD({t['simd']}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({t['weight_width']}),
        .ACCU_WIDTH({t['accu_width']}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst (
        .ap_clk(ap_clk),
        .ap_clk2x(1'b0),
        .ap_rst_n(rst_n),
        .s_axis_weights_tdata(w_dout),
        .s_axis_weights_tvalid(wgt_tvalid),
        .s_axis_weights_tready(wgt_tready),
        .s_axis_input_tdata(a_dout),
        .s_axis_input_tvalid(in_tvalid),
        .s_axis_input_tready(in_tready),
        .m_axis_output_tdata(out_tdata),
        .m_axis_output_tvalid(out_tvalid),
        .m_axis_output_tready(out_tready)
    );
endmodule
"""


def _mvu_inst(t, fb, i, act_expr="a_dout"):
    """One ``mvu_vvu_axi`` instance for tile ``i`` with the tile's fold params,
    wired to that tile's memstream (weights) and its activation input ``act_expr``
    (the whole ``a_dout`` for N-tiling/broadcast, or a per-tile slice for K-tiling).
    """
    return f"""    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}),
        .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({t['mh']}), .PE({t['pe']}), .SIMD({t['simd']}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({t['weight_width']}),
        .ACCU_WIDTH({t['accu_width']}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst_{i} (
        .ap_clk(ap_clk),
        .ap_clk2x(1'b0),
        .ap_rst_n(rst_n),
        .s_axis_weights_tdata(w_odat_{i}),
        .s_axis_weights_tvalid(wgt_tvalid_{i}),
        .s_axis_weights_tready(wgt_tready_{i}),
        .s_axis_input_tdata({act_expr}),
        .s_axis_input_tvalid(in_tvalid),
        .s_axis_input_tready(in_tready[{i}]),
        .m_axis_output_tdata(out_tdata_{i}),
        .m_axis_output_tvalid(out_tvalid[{i}]),
        .m_axis_output_tready(out_tready)
    );
"""


def _ws_tile_block(t, fb, wbits, pbits, wmem, i, init_file, act_expr="a_dout", label=None):
    """RTL for tile ``i``: its own memstream (baked weights for the tile's slice),
    the ce-gated weight handshake, the slice of ``p_din`` the tile drives, and the
    ``mvu_vvu_axi`` instance fed activation ``act_expr``."""
    lo, hi = i * pbits, (i + 1) * pbits - 1
    col0, col1 = i * t["mh"], (i + 1) * t["mh"] - 1
    zero = "{%d{1'b0}}" % wbits
    tag = label if label is not None else f"output columns [{col0}, {col1}]"
    return f"""    // ---- tile {i}: {tag} ----
    wire [{wbits - 1}:0] w_odat_{i};
    wire                 w_ovld_{i}, w_ordy_{i}, wgt_tvalid_{i}, wgt_tready_{i};
    wire [{pbits - 1}:0] out_tdata_{i};
    memstream #(
        .DEPTH({wmem}), .WIDTH({wbits}),
        .INIT_FILE("{init_file}"), .RAM_STYLE("auto")
    ) wmem_{i} (
        .clk(ap_clk), .rst(ap_rst),
        .config_ce(1'b0), .config_we(1'b0), .config_address(32'd0), .config_d0({zero}),
        .config_rack(), .config_q0(),
        .ordy(w_ordy_{i}), .ovld(w_ovld_{i}), .odat(w_odat_{i})
    );
    assign wgt_tvalid_{i} = ap_ce & w_ovld_{i};   // ce-gated memstream -> weight AXIS
    assign w_ordy_{i}     = ap_ce & wgt_tready_{i};
    assign p_din[{hi}:{lo}] = out_tdata_{i};      // tile output -> concatenated result beat
{_mvu_inst(t, fb, i, act_expr)}"""


def _generate_kt_shim(t, module_name, fb, wbits, abits, pbits, init_files, n_tiles, k_tiles, m):
    """K-tiled (and combined N+K) weight-stationary grid shim: an ``n_tiles``×``k_tiles`` grid
    of MVU cores. Tile (j,i) reduces K-slice i (MW=K_pad/k_tiles) for N-slice j (MH=N_tile),
    each a baked ``memstream`` (DEPTH = wmem = SF_tile*NF) holding that (j,i) weight block. The
    activation arrives as ``SF_tile`` beats of ``k_tiles*abits`` per vector, K-sliced (tile
    reads lane ``[i*abits +: abits]``) and broadcast across N-slices. Outputs concatenate into
    ``n_tiles*k_tiles*PB`` partials — summed over K and concatenated over N in the drain.
    Reduces to the pure K-tiled shim at n_tiles=1."""
    ntiles = n_tiles * k_tiles
    if not init_files or any(not f for f in init_files) or len(init_files) != ntiles:
        raise ValueError(f"grid shim needs {ntiles} (= n_tiles*k_tiles) memstream init file(s)")
    wmem = t["wmem"]
    a_total = k_tiles * abits
    pb_total = ntiles * pbits
    blocks = "\n".join(
        _ws_tile_block(t, fb, wbits, pbits, wmem, j * k_tiles + i, init_files[j * k_tiles + i],
                       act_expr=f"a_dout[{(i + 1) * abits - 1}:{i * abits}]",
                       label=f"N-slice {j} K-slice {i} partial ({t['mh']} cols)")
        for j in range(n_tiles) for i in range(k_tiles))

    def _w(n):
        return max(1, (n - 1).bit_length())
    sf_tile = t["mw"] // t["simd"]
    in_total = m * sf_tile           # activation beats/node (matches feed_a's m*SF_tile reads)
    run_total = m * t["nf"]          # output beats/node (matches requant's m*NF reads)
    return f"""// Generated by gemm-ip-gen (mvau target). Weight-stationary grid shim:
// {n_tiles}x{k_tiles} (N-tiles x K-tiles) MVU cores; tile (j,i) reduces K-slice i (MW={t['mw']})
// for N-slice j ({t['mh']} cols); activation K-sliced + broadcast over N, partials concatenated
// (summed over K + concatenated over N in the drain).
// Tile: MW(K/tile)={t['mw']} MH(N/tile)={t['mh']} PE={t['pe']} SIMD={t['simd']} \
core={t['compute_core']} ACCU={t['accu_width']} WMEM={wmem} N_TILES={n_tiles} K_TILES={k_tiles}
// Module name MUST equal the JSON c_function_name (Vitis instantiates by it).
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,     // active-high
    input  wire                 ap_ce,      // active-high clock enable / stall
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // activation FIFO (input)  {a_total} = K_TILES * ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{a_total - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // output FIFO (output)     {pb_total} = N_TILES*K_TILES * ceil(PE*ACCU_WIDTH/8)*8 (partials)
    output wire [{pb_total - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;

    // ---- ap_ctrl_chain invocation-level FSM: IDLE <-> RUN, one node/invocation ----
    localparam IDLE = 1'd0, RUN = 1'd1;
    reg                        state = IDLE;
    reg                        done_r = 0;
    reg  [{_w(in_total + 1) - 1}:0]  icnt = 0;   // activation beats accepted this node
    reg  [{_w(run_total + 1) - 1}:0]  ocnt = 0;   // output beats produced this node

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; icnt <= 0; ocnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= RUN; icnt <= 0; ocnt <= 0;
            end else if (state == RUN) begin
                if (in_tvalid & (&in_tready)) icnt <= icnt + 1'b1;
                if (p_write) begin
                    if (ocnt == {run_total - 1}) begin
                        state <= IDLE; done_r <= 1'b1;
                    end else ocnt <= ocnt + 1'b1;
                end
            end
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

    // gate on icnt too: stop pulling A beats once this node's {in_total} beats
    // are accepted, even if the next node's rows are already queued in the FIFO.
    wire in_open = (state == RUN) & (icnt != {in_total});

    // one wide activation beat feeds all tiles (each its own K-lane slice); lockstep.
    wire in_tvalid  = ap_ce & in_open & a_empty_n;
    wire out_tready = ap_ce & p_full_n;
    wire [{ntiles - 1}:0] in_tready;
    wire [{ntiles - 1}:0] out_tvalid;
    assign a_read  = ap_ce & in_open & (&in_tready);
    assign p_write = ap_ce & (&out_tvalid) & p_full_n;   // count only real transfers

{blocks}endmodule
"""


def generate_two_operand_shim(shape, module_name="mvau_core", force_behavioral=True,
                              tile=None, plan=None, **plan_kwargs):
    """Emit the two-operand (``gemm_stream``) shim: A and B both runtime activation
    streams. B takes the MVU weight port, loaded at runtime into ``memstream`` via its
    addressed config-write port, then replayed across the M rows of A (B-stationary).

    The HLS wrapper is a pure passthrough for both operands; all matmul mechanics stay
    in RTL. B arrives as **N-wide beats in K-row order** (row-major ``B[k][:]``). The load
    FSM buffers a band of SIMD consecutive K-rows (all N columns), then emits the NF
    memstream words for that band (one per PE-column block) at strided address
    ``nf*SF+sf``, bit ``(pe*SIMD+s)*WW`` = ``B[sf*SIMD+s][nf*PE+pe]``.

    Scope: single tile, any (PE, SIMD, SF, NF); no N/K-tiling. The controller runs
    FILL (gather SIMD rows; config_ce held high so the stream pointer stays at 0) ->
    WRITE (config_we the NF words of the band) -> ... -> DRAIN (let the last write
    commit) -> RUN (config_ce low, activations stream, memstream replays across M),
    then reloads for the next node. NF=1 collapses WRITE to a single word per band."""
    t = tile if tile is not None else _geom.resolve_plan(shape, **plan_kwargs)["tile"]
    p = plan if plan is not None else _geom.resolve_plan(shape, **plan_kwargs)
    fb = 1 if force_behavioral else 0
    N = p["n"]
    M = p["num_input_vectors"]
    PE, SIMD, SF, NF = t["pe"], t["simd"], t["sf"], t["nf"]
    WW, ACCU = t["weight_width"], t["accu_width"]
    WB = t["weight_stream_width_ba"]     # memstream word width (PE*SIMD*WW, byte-aligned)
    AB = t["input_stream_width_ba"]      # activation beat (SIMD*AW)
    PB = t["output_stream_width_ba"]     # output beat (PE*ACCU)
    BB = ((N * WW) + 7) // 8 * 8         # B beat: N weight codes, byte-aligned
    DEPTH = NF * SF
    # This shim serves the temporal-fold case (DEPTH = NF*SF >= 2). The fully-spatial
    # DEPTH==1 case (one weight word/vector) is served by the K-tiled register shim with
    # gk=1 (a memstream cannot be config-written at DEPTH=1), routed in generate_two_operand_pkg.
    if DEPTH < 2:
        raise NotImplementedError(
            "single-tile two-operand shim requires DEPTH=NF*SF>=2; the fully-spatial "
            "DEPTH==1 case is handled by the K-tiled register shim (gk=1).")
    run_total = M * NF                    # output beats per node (NF beats per vector)

    def _w(n):                            # bit-width to hold values 0..n-1
        return max(1, (n - 1).bit_length())
    wa_decl = ""
    cfg_we_expr = "ap_ce & (state == WRITE)"
    cfg_addr_expr = f"nfc * {SF} + sfc"
    write_body = f"""                WRITE: begin      // emit the NF words of this band, one per cycle
                    if (nfc == {NF - 1}) begin
                        nfc <= 0;
                        if (sfc == {SF - 1}) begin sfc <= 0; state <= DRAIN; dcnt <= 0; end
                        else begin sfc <= sfc + 1'b1; state <= FILL; end
                    end else nfc <= nfc + 1'b1;
                end"""
    fill_reset = "sc <= 0; nfc <= 0; state <= WRITE;"
    # combinational pack of the current band's word for column block nfc:
    #   wword[(pe*SIMD+s)*WW +: WW] = band[s][(nfc*PE+pe)*WW +: WW]
    fill = "\n".join(
        f"        wword[{(pe * SIMD + s) * WW} +: {WW}] = band[{s}][nfc*{PE * WW} + {pe * WW} +: {WW}];"
        for pe in range(PE) for s in range(SIMD))
    return f"""// Generated by gemm-ip-gen (mvau target). Two-operand (gemm_stream) shim:
// A + B both runtime streams; B loaded into memstream at runtime, replayed across M.
// Tile: MW(K)={t['mw']} MH(N)={N} PE={PE} SIMD={SIMD} SF={SF} NF={NF} \
core={t['compute_core']} ACCU={ACCU} DEPTH={DEPTH} M={M}
// Module name MUST equal the JSON c_function_name (Vitis instantiates by it).
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,     // active-high
    input  wire                 ap_ce,      // active-high clock enable / stall
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // activation FIFO (input)  {AB} = ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{AB - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // B FIFO (input)           {BB} = ceil(N*WEIGHT_WIDTH/8)*8 (one N-wide K-row per beat)
    input  wire [{BB - 1}:0] b_dout,
    input  wire                 b_empty_n,
    output wire                 b_read,
    // output FIFO (output)     {PB} = ceil(PE*ACCU_WIDTH/8)*8
    output wire [{PB - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;
    localparam [2:0] IDLE = 3'd0, FILL = 3'd1, WRITE = 3'd2, DRAIN = 3'd3, RUN = 3'd4;

    reg  [2:0]            state = IDLE;
    reg                    done_r = 0;      // ap_done pending, cleared by ap_continue
    reg  [{_w(SIMD) - 1}:0]  sc = 0;    // lane within band (0..SIMD-1)
    reg  [{_w(SF) - 1}:0]  sfc = 0;     // band index (0..SF-1)
    reg  [{_w(NF) - 1}:0]  nfc = 0;     // column block within band (0..NF-1)
    reg  [1:0]            dcnt = 0;     // drain counter
    reg  [{_w(run_total) - 1}:0]  ocnt = 0;   // output beats seen this node
    reg  [{_w(M * SF + 1) - 1}:0]  icnt = 0;       // A beats accepted this node (M*SF)
{wa_decl}
    // band buffer: SIMD consecutive N-wide K-rows (all columns), refilled per band
    reg  [{BB - 1}:0]  band [0:{SIMD - 1}];

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    // b handshake: consume a B beat only while filling a band
    assign b_read = ap_ce & (state == FILL) & b_empty_n;

    // current memstream word for column block nfc, packed from the buffered band
    reg  [{WB - 1}:0]  wword;
    always @* begin
        wword = {{{WB}{{1'b0}}}};
{fill}
    end

    // memstream config-write load port (config_ce held through FILL/WRITE/DRAIN so the
    // stream pointer stays frozen at 0 until RUN; config_we pulses one word per WRITE cycle)
    wire        cfg_ce = ap_ce & (state == FILL || state == WRITE || state == DRAIN);
    wire        cfg_we = {cfg_we_expr};
    wire [31:0] cfg_addr = {cfg_addr_expr};   // memstream word address
    wire [{WB - 1}:0] cfg_d0 = wword;

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; sc <= 0; sfc <= 0; nfc <= 0; dcnt <= 0; ocnt <= 0; icnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= FILL; sc <= 0; sfc <= 0; nfc <= 0; dcnt <= 0; ocnt <= 0; icnt <= 0;
            end else case (state)
                IDLE: ;
                FILL: if (b_read) begin
                    band[sc] <= b_dout;
                    if (sc == {SIMD - 1}) begin {fill_reset} end
                    else sc <= sc + 1'b1;
                end
{write_body}
                DRAIN: begin
                    dcnt <= dcnt + 1'b1;
                    if (dcnt == 2'd1) begin state <= RUN; ocnt <= 0; icnt <= 0; end
                end
                RUN: begin
                    if (in_tvalid & in_tready) icnt <= icnt + 1'b1;
                    if (p_write) begin
                        if (ocnt == {run_total - 1}) begin state <= IDLE; done_r <= 1'b1; end
                        else ocnt <= ocnt + 1'b1;
                    end
                end
            endcase
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

    // ---- weight ROM (runtime-loaded), MVU core, run-phase handshakes ----
    wire [{WB - 1}:0] w_odat;
    wire              w_ovld, w_ordy, wgt_tvalid, wgt_tready;
    wire              in_tvalid, in_tready, out_tvalid, out_tready;
    wire [{PB - 1}:0] out_tdata;

    memstream #(
        .DEPTH({DEPTH}), .WIDTH({WB}), .INIT_FILE(""), .RAM_STYLE("auto")
    ) wmem (
        .clk(ap_clk), .rst(ap_rst),
        .config_ce(cfg_ce), .config_we(cfg_we), .config_address(cfg_addr), .config_d0(cfg_d0),
        .config_rack(), .config_q0(),
        .ordy(w_ordy), .ovld(w_ovld), .odat(w_odat)
    );

    // RUN-phase AXIS binding (frozen during LOAD/DRAIN so the core stays idle)
    wire run = (state == RUN);
    // gate the A handshake on icnt too: stop pulling A beats once this node's M*SF
    // beats are accepted, even if the next node's rows are already queued in the FIFO.
    wire in_open = run & (icnt != {M * SF});
    assign wgt_tvalid = ap_ce & run & w_ovld;
    assign w_ordy     = ap_ce & run & wgt_tready;
    assign in_tvalid  = ap_ce & in_open & a_empty_n;
    assign a_read     = ap_ce & in_open & in_tready;
    assign out_tready = ap_ce & p_full_n;
    assign p_write    = ap_ce & out_tvalid & p_full_n;   // count only real transfers
    assign p_din      = out_tdata;

    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}),
        .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({N}), .PE({t['pe']}), .SIMD({SIMD}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({WW}),
        .ACCU_WIDTH({ACCU}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst (
        .ap_clk(ap_clk),
        .ap_clk2x(1'b0),
        .ap_rst_n(rst_n),
        .s_axis_weights_tdata(w_odat),
        .s_axis_weights_tvalid(wgt_tvalid),
        .s_axis_weights_tready(wgt_tready),
        .s_axis_input_tdata(a_dout),
        .s_axis_input_tvalid(in_tvalid),
        .s_axis_input_tready(in_tready),
        .m_axis_output_tdata(out_tdata),
        .m_axis_output_tvalid(out_tvalid),
        .m_axis_output_tready(out_tready)
    );
endmodule
"""


def _2op_grid_memstream_shim(t, p, module_name, force_behavioral, nt, gk, sf_tile):
    """General tiled two-operand shim (DEPTH_tile = SF_tile*NF >= 2): an nt×gk grid of MVU
    cores. Tile (j,i) reduces K-slice i (rows [i*MW_tile:(i+1)*MW_tile)) for N-slice j
    (columns [j*N_tile:(j+1)*N_tile)), each a runtime ``memstream`` (DEPTH=SF_tile*NF) loaded
    from B and replayed across the M vectors. One shared FSM loads the K-slices sequentially,
    writing all nt N-slices of the current K-slice in parallel; then all cores RUN in lockstep.
    The drain sums the gk K-partials per column and concatenates the nt N-slices. Reduces to
    the single-tile / K-tiled / N-tiled shims at (nt=gk=1) / (nt=1) / (gk=1)."""
    fb = 1 if force_behavioral else 0
    N, M = p["n"], p["num_input_vectors"]
    NTILE = N // nt
    PE, SIMD, WW, ACCU = t["pe"], t["simd"], t["weight_width"], t["accu_width"]
    NF = t["nf"]
    WB = t["weight_stream_width_ba"]
    AB = t["input_stream_width_ba"]
    PB = t["output_stream_width_ba"]
    BB = ((N * WW) + 7) // 8 * 8
    A_TOTAL, PB_TOTAL = gk * AB, nt * gk * PB
    NTILES = nt * gk
    DEPTH = sf_tile * NF
    run_total = M * NF

    def _w(n):
        return max(1, (n - 1).bit_length())

    # nt combinational words: wword_j packs N-slice j's column block nfc from the current band
    #   wword_j[(pe*SIMD+s)*WW +: WW] = band[s][(j*N_tile + nfc*PE + pe)*WW +: WW]
    def _wword(j):
        body = "\n".join(
            f"        wword_{j}[{(pe * SIMD + s) * WW} +: {WW}] = "
            f"band[{s}][{j * NTILE * WW} + nfc*{PE * WW} + {pe * WW} +: {WW}];"
            for pe in range(PE) for s in range(SIMD))
        return (f"    reg  [{WB - 1}:0]  wword_{j};\n    always @* begin\n"
                f"        wword_{j} = {{{WB}{{1'b0}}}};\n{body}\n    end")
    wwords = "\n".join(_wword(j) for j in range(nt))

    def _tile(j, i):
        idx = j * gk + i
        return f"""    // ---- tile (N{j},K{i}): cols [{j * NTILE},{(j + 1) * NTILE - 1}] rows [{i * t['mw']},{(i + 1) * t['mw'] - 1}] ----
    wire [{WB - 1}:0] w_odat_{idx};
    wire              w_ovld_{idx}, w_ordy_{idx}, wgt_tvalid_{idx}, wgt_tready_{idx};
    wire [{PB - 1}:0] out_tdata_{idx};
    assign p_din[{(idx + 1) * PB - 1}:{idx * PB}] = out_tdata_{idx};
    memstream #(
        .DEPTH({DEPTH}), .WIDTH({WB}), .INIT_FILE(""), .RAM_STYLE("auto")
    ) wmem_{idx} (
        .clk(ap_clk), .rst(ap_rst),
        .config_ce(ap_ce & (state != RUN) & (tic == {i})),
        .config_we(ap_ce & (state == WRITE) & (tic == {i})),
        .config_address(nfc * {sf_tile} + sfc), .config_d0(wword_{j}),
        .config_rack(), .config_q0(),
        .ordy(w_ordy_{idx}), .ovld(w_ovld_{idx}), .odat(w_odat_{idx})
    );
    assign wgt_tvalid_{idx} = ap_ce & run & w_ovld_{idx};
    assign w_ordy_{idx}     = ap_ce & run & wgt_tready_{idx};
    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}), .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({NTILE}), .PE({PE}), .SIMD({SIMD}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({WW}), .ACCU_WIDTH({ACCU}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst_{idx} (
        .ap_clk(ap_clk), .ap_clk2x(1'b0), .ap_rst_n(rst_n),
        .s_axis_weights_tdata(w_odat_{idx}), .s_axis_weights_tvalid(wgt_tvalid_{idx}), .s_axis_weights_tready(wgt_tready_{idx}),
        .s_axis_input_tdata(a_dout[{(i + 1) * AB - 1}:{i * AB}]),
        .s_axis_input_tvalid(in_tvalid), .s_axis_input_tready(in_tready[{idx}]),
        .m_axis_output_tdata(out_tdata_{idx}), .m_axis_output_tvalid(out_tvalid[{idx}]), .m_axis_output_tready(out_tready)
    );"""
    tiles = "\n".join(_tile(j, i) for j in range(nt) for i in range(gk))

    return f"""// Generated by gemm-ip-gen (mvau target). General tiled two-operand (gemm_stream) shim:
// {nt}x{gk} (N-tiles x K-tiles) MVU cores, each a runtime memstream (DEPTH=SF_tile*NF={DEPTH}).
// Tile (j,i) reduces K-slice i (MW={t['mw']}) for N-slice j (N_tile={NTILE} cols); K-partials
// summed + N-slices concatenated in the drain. B loaded per K-slice, replayed across M={M}.
// Tile: MW={t['mw']} MH(N_tile)={NTILE} PE={PE} SIMD={SIMD} \
SF_tile={sf_tile} NF={NF} N_TILES={nt} K_TILES={gk} core={t['compute_core']} ACCU={ACCU}
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,
    input  wire                 ap_ce,
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // wide activation FIFO (input)  {A_TOTAL} = K_TILES * ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{A_TOTAL - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // B FIFO (input)                {BB} = ceil(N*WEIGHT_WIDTH/8)*8 (N-wide K-row beats)
    input  wire [{BB - 1}:0] b_dout,
    input  wire                 b_empty_n,
    output wire                 b_read,
    // output FIFO (output)          {PB_TOTAL} = N_TILES*K_TILES * ceil(PE*ACCU_WIDTH/8)*8 (partials)
    output wire [{PB_TOTAL - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;
    localparam [2:0] IDLE = 3'd0, FILL = 3'd1, WRITE = 3'd2, DRAIN = 3'd3, RUN = 3'd4;

    reg  [2:0]            state = IDLE;
    reg                    done_r = 0;      // ap_done pending, cleared by ap_continue
    reg  [{_w(SIMD) - 1}:0]  sc = 0;    // lane within band (0..SIMD-1)
    reg  [{_w(sf_tile) - 1}:0]  sfc = 0; // band within K-slice (0..SF_tile-1)
    reg  [{_w(NF) - 1}:0]  nfc = 0;      // column block within band (0..NF-1)
    reg  [{_w(gk) - 1}:0]  tic = 0;      // K-slice being loaded (0..gk-1)
    reg  [1:0]            dcnt = 0;
    reg  [{_w(run_total) - 1}:0]  ocnt = 0;
    reg  [{_w(M * sf_tile + 1) - 1}:0]  icnt = 0;  // A beats accepted this node (M*SF_tile)

    reg  [{BB - 1}:0]  band [0:{SIMD - 1}];   // SIMD N-wide K-rows of the current band

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    assign b_read = ap_ce & (state == FILL) & b_empty_n;

{wwords}

    wire run = (state == RUN);
    // gate on icnt too: stop pulling A beats once this node's M*SF_tile beats are
    // accepted, so a queued next-node row isn't fed to the MVU against the current B.
    wire in_open = run & (icnt != {M * sf_tile});
    wire in_tvalid  = ap_ce & in_open & a_empty_n;
    wire out_tready = ap_ce & p_full_n;
    wire [{NTILES - 1}:0] in_tready;
    wire [{NTILES - 1}:0] out_tvalid;
    assign a_read  = ap_ce & in_open & (&in_tready);
    assign p_write = ap_ce & (&out_tvalid) & p_full_n;   // count only real transfers

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; sc <= 0; sfc <= 0; nfc <= 0; tic <= 0; dcnt <= 0; ocnt <= 0; icnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= FILL; sc <= 0; sfc <= 0; nfc <= 0; tic <= 0; dcnt <= 0; ocnt <= 0; icnt <= 0;
            end else case (state)
                IDLE: ;
                FILL: if (b_read) begin
                    band[sc] <= b_dout;
                    if (sc == {SIMD - 1}) begin sc <= 0; nfc <= 0; state <= WRITE; end
                    else sc <= sc + 1'b1;
                end
                WRITE: begin   // emit the NF words of this band, one per cycle
                    if (nfc == {NF - 1}) begin
                        nfc <= 0;
                        if (sfc == {sf_tile - 1}) begin
                            sfc <= 0;
                            if (tic == {gk - 1}) begin tic <= 0; state <= DRAIN; dcnt <= 0; end
                            else begin tic <= tic + 1'b1; state <= FILL; end
                        end else begin sfc <= sfc + 1'b1; state <= FILL; end
                    end else nfc <= nfc + 1'b1;
                end
                DRAIN: begin
                    dcnt <= dcnt + 1'b1;
                    if (dcnt == 2'd1) begin state <= RUN; ocnt <= 0; icnt <= 0; end
                end
                RUN: begin
                    if (in_tvalid & (&in_tready)) icnt <= icnt + 1'b1;
                    if (p_write) begin
                        if (ocnt == {run_total - 1}) begin state <= IDLE; done_r <= 1'b1; end
                        else ocnt <= ocnt + 1'b1;
                    end
                end
            endcase
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

{tiles}
endmodule
"""


def _2op_grid_register_shim(t, p, module_name, force_behavioral, nt, gk):
    """Fully-spatial per-tile two-operand grid (DEPTH_tile = SF_tile*NF == 1): an nt×gk grid of
    MVU cores, each fed a single latched weight word (a memstream cannot be config-written at
    DEPTH=1). B is loaded per K-slice — the nt N-slice words latched in parallel — then replayed
    from the registers across the M vectors. Activation is K-sliced (a_dout[i*AB +: AB]) and
    broadcast across N-slices; partials are summed over K and concatenated over N in the drain.
    Reduces to the K-tiled register path at nt=1."""
    fb = 1 if force_behavioral else 0
    N, M = p["n"], p["num_input_vectors"]
    NTILE = N // nt
    PE, SIMD, WW, ACCU = t["pe"], t["simd"], t["weight_width"], t["accu_width"]
    WB = t["weight_stream_width_ba"]
    AB = t["input_stream_width_ba"]
    PB = t["output_stream_width_ba"]
    BB = ((N * WW) + 7) // 8 * 8
    A_TOTAL, PB_TOTAL = gk * AB, nt * gk * PB
    NTILES = nt * gk

    def _w(n):
        return max(1, (n - 1).bit_length())

    # nt combinational words: wword_j packs N-slice j's PE columns from the band (NF=1)
    def _wword(j):
        body = "\n".join(
            f"        wword_{j}[{(pe * SIMD + s) * WW} +: {WW}] = band[{s}][{(j * NTILE + pe) * WW} +: {WW}];"
            for pe in range(PE) for s in range(SIMD))
        return (f"    reg  [{WB - 1}:0]  wword_{j};\n    always @* begin\n"
                f"        wword_{j} = {{{WB}{{1'b0}}}};\n{body}\n    end")
    wwords = "\n".join(_wword(j) for j in range(nt))
    latch = "\n".join(f"                    wreg[{j} * {gk} + ti] <= wword_{j};" for j in range(nt))

    def _tile(j, i):
        idx = j * gk + i
        return f"""    wire                 wgt_tready_{idx};
    wire [{PB - 1}:0] out_tdata_{idx};
    assign p_din[{(idx + 1) * PB - 1}:{idx * PB}] = out_tdata_{idx};   // tile (N{j},K{i}) partial
    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}), .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({NTILE}), .PE({PE}), .SIMD({SIMD}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({WW}), .ACCU_WIDTH({ACCU}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst_{idx} (
        .ap_clk(ap_clk), .ap_clk2x(1'b0), .ap_rst_n(rst_n),
        .s_axis_weights_tdata(wreg[{idx}]), .s_axis_weights_tvalid(ap_ce & run), .s_axis_weights_tready(wgt_tready_{idx}),
        .s_axis_input_tdata(a_dout[{(i + 1) * AB - 1}:{i * AB}]),
        .s_axis_input_tvalid(in_tvalid), .s_axis_input_tready(in_tready[{idx}]),
        .m_axis_output_tdata(out_tdata_{idx}), .m_axis_output_tvalid(out_tvalid[{idx}]), .m_axis_output_tready(out_tready)
    );"""
    tiles = "\n".join(_tile(j, i) for j in range(nt) for i in range(gk))

    return f"""// Generated by gemm-ip-gen (mvau target). Fully-spatial two-operand grid (DEPTH_tile=1):
// {nt}x{gk} (N-tiles x K-tiles) MVU cores, each fed one latched weight word; B loaded per
// K-slice (nt N-slices in parallel), replayed from registers across M={M}. K-partials summed +
// N-slices concatenated in the drain. Tile: MW={t['mw']} MH(N_tile)={NTILE} PE={PE} SIMD={SIMD} \
N_TILES={nt} K_TILES={gk} core={t['compute_core']} ACCU={ACCU}
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,
    input  wire                 ap_ce,
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // wide activation FIFO (input)  {A_TOTAL} = K_TILES * ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{A_TOTAL - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // B FIFO (input)                {BB} = ceil(N*WEIGHT_WIDTH/8)*8 (N-wide K-row beats)
    input  wire [{BB - 1}:0] b_dout,
    input  wire                 b_empty_n,
    output wire                 b_read,
    // output FIFO (output)          {PB_TOTAL} = N_TILES*K_TILES * ceil(PE*ACCU_WIDTH/8)*8 (partials)
    output wire [{PB_TOTAL - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;
    localparam [1:0] IDLE = 2'd0, FILL = 2'd1, LATCH = 2'd2, RUN = 2'd3;

    reg  [1:0]            state = IDLE;
    reg                    done_r = 0;      // ap_done pending, cleared by ap_continue
    reg  [{_w(SIMD) - 1}:0]  sc = 0;    // lane within band (0..SIMD-1)
    reg  [{_w(gk) - 1}:0]  ti = 0;      // K-slice being loaded (0..gk-1)
    reg  [{_w(M) - 1}:0]  ocnt = 0;     // output beats seen this node (NF=1 -> M)
    reg  [{_w(M + 1) - 1}:0]  icnt = 0;     // A beats accepted this node (NF=1 -> M)

    reg  [{BB - 1}:0]  band [0:{SIMD - 1}];   // SIMD N-wide K-rows of the current K-slice
    reg  [{WB - 1}:0]  wreg [0:{NTILES - 1}]; // per-tile latched weight word

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    assign b_read = ap_ce & (state == FILL) & b_empty_n;

{wwords}

    wire        run = (state == RUN);
    // gate on icnt too: stop pulling A beats once this node's M beats are accepted, so
    // a queued next-node row isn't fed to the MVU against the current B.
    wire in_open = run & (icnt != {M});
    wire in_tvalid  = ap_ce & in_open & a_empty_n;
    wire out_tready = ap_ce & p_full_n;
    wire [{NTILES - 1}:0] in_tready;
    wire [{NTILES - 1}:0] out_tvalid;
    assign a_read  = ap_ce & in_open & (&in_tready);
    assign p_write = ap_ce & (&out_tvalid) & p_full_n;   // count only real transfers

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; sc <= 0; ti <= 0; ocnt <= 0; icnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= FILL; sc <= 0; ti <= 0; ocnt <= 0; icnt <= 0;
            end else case (state)
                IDLE: ;
                FILL: if (b_read) begin
                    band[sc] <= b_dout;
                    if (sc == {SIMD - 1}) begin sc <= 0; state <= LATCH; end
                    else sc <= sc + 1'b1;
                end
                LATCH: begin      // K-slice band complete -> latch all nt N-slice words
{latch}
                    if (ti == {gk - 1}) begin ti <= 0; state <= RUN; ocnt <= 0; icnt <= 0; end
                    else begin ti <= ti + 1'b1; state <= FILL; end
                end
                RUN: begin
                    if (in_tvalid & (&in_tready)) icnt <= icnt + 1'b1;
                    if (p_write) begin
                        if (ocnt == {M - 1}) begin state <= IDLE; done_r <= 1'b1; end
                        else ocnt <= ocnt + 1'b1;
                    end
                end
            endcase
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

{tiles}
endmodule
"""


def generate_two_operand_kt_shim(shape, module_name="mvau_core", force_behavioral=True,
                                 tile=None, plan=None, **plan_kwargs):
    """K-tiled two-operand shim: ``gk`` MVU cores each reduce a K-slice for all N columns,
    their partials concatenated (summed in the drain). Both operands are runtime streams.

    Two per-tile weight paths, by the per-tile fold depth ``DEPTH_tile = SF_tile*NF``:

    * ``DEPTH_tile == 1`` (fully-spatial per tile, SF_tile=1 NF=1): one weight word per tile,
      driven from a latched register (a memstream cannot be config-written at DEPTH=1). A
      arrives as one wide beat of ``gk*AB``.
    * ``DEPTH_tile >= 2`` (SF_tile>1 and/or NF>1): each tile is a runtime ``memstream``
      (DEPTH=SF_tile*NF) loaded from its K-slice of B, then replayed across the M vectors —
      i.e. ``gk`` copies of the single-tile temporal shim, sharing one sequential-load FSM.
      A arrives as ``gk*AB`` per K-band, SF_tile bands/vector; output is NF beats/vector.

    B arrives as N-wide K-row beats (K_pad rows total, row-major): tile ``i`` owns rows
    ``[i*MW_tile : (i+1)*MW_tile)``; A lane ``[i*AB +: AB]`` is tile ``i``'s SIMD slice."""
    t = tile if tile is not None else _geom.resolve_plan(shape, **plan_kwargs)["tile"]
    p = plan if plan is not None else _geom.resolve_plan(shape, **plan_kwargs)
    gk = p["k_tiles"]
    sf_tile = t["mw"] // t["simd"]
    if sf_tile * t["nf"] >= 2:
        return _2op_grid_memstream_shim(t, p, module_name, force_behavioral, 1, gk, sf_tile)
    return _2op_grid_register_shim(t, p, module_name, force_behavioral, 1, gk)


def generate_two_operand_nt_shim(shape, module_name="mvau_core", force_behavioral=True,
                                 tile=None, plan=None, **plan_kwargs):
    """N-tiled (and combined N+K) two-operand shim: dispatch to the general nt×gk grid.

    N-tiling is an explicit-pin feature — the mapper never chooses copies.N>1 for a streamed
    layer — so it composes with whatever K-tiling the fold needs. The grid memstream shim
    covers any per-tile fold with DEPTH_tile = SF_tile*NF >= 2; the DEPTH==1 (SF_tile=NF=1)
    grid uses latched registers."""
    t = tile if tile is not None else _geom.resolve_plan(shape, **plan_kwargs)["tile"]
    p = plan if plan is not None else _geom.resolve_plan(shape, **plan_kwargs)
    nt, gk = p["n_tiles"], p["k_tiles"]
    sf_tile = t["mw"] // t["simd"]
    if sf_tile * t["nf"] >= 2:
        return _2op_grid_memstream_shim(t, p, module_name, force_behavioral, nt, gk, sf_tile)
    return _2op_grid_register_shim(t, p, module_name, force_behavioral, nt, gk)


def _generate_ws_shim(t, module_name, fb, wbits, abits, pbits, init_files, n_tiles, m):
    """Weight-stationary shim: ``n_tiles`` FINN ``memstream`` + ``mvu_vvu_axi``
    tiles stitched in RTL. Each memstream (baked from ``init_files[i]``) replaces
    the external weight FIFO for its N-column slice and drives its tile's
    ``s_axis_weights`` directly.

    memstream ``WIDTH`` = the byte-aligned weight-stream width (the packed
    PE*SIMD*WEIGHT_WIDTH weights sit in the low bits, high bits zero); ``DEPTH`` =
    WMEM = NF*SF words per tile, re-streamed cyclically so every input vector
    re-reads the same weights.

    Stitching (all tiles are identical modules fed identical activations with
    identical output backpressure, so they run in lockstep):
      * one activation FIFO broadcasts to every tile; ``a_read`` advances it only
        when every tile asserts ``tready`` (``&in_tready``).
      * the tile outputs concatenate into one ``{n_tiles}*PB``-wide ``p_din`` beat
        (tile ``i`` at ``[i*PB +: PB]``); ``p_write`` fires when every tile has a
        beat (``&out_tvalid``). Generalizes temp_space/mvau-ws (cosim PASS)."""
    if not init_files or any(not f for f in init_files):
        raise ValueError("weight-stationary shim requires an init_file per tile "
                         "(memstream $readmemh path)")
    if len(init_files) != n_tiles:
        raise ValueError(f"expected {n_tiles} init file(s), got {len(init_files)}")
    wmem = t["wmem"]
    pb_total = n_tiles * pbits
    blocks = "\n".join(
        _ws_tile_block(t, fb, wbits, pbits, wmem, i, init_files[i]) for i in range(n_tiles))

    def _w(n):
        return max(1, (n - 1).bit_length())
    in_total = m * t["sf"]      # activation beats/node (matches feed_a's m*SF reads)
    run_total = m * t["nf"]     # output beats/node (matches requant's m*NF reads)
    return f"""// Generated by gemm-ip-gen (mvau target). Weight-stationary shim: {n_tiles} FINN
// MVU tile(s) -- each a memstream (baked weights) + mvu_vvu_axi -- stitched in RTL.
// Shared activation broadcast in; per-tile outputs concatenated into one beat.
// Tile: MW(K)={t['mw']} MH(N/tile)={t['mh']} PE={t['pe']} SIMD={t['simd']} \
core={t['compute_core']} ACCU={t['accu_width']} WMEM={wmem} N_TILES={n_tiles}
// Module name MUST equal the JSON c_function_name (Vitis instantiates by it).
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,     // active-high
    input  wire                 ap_ce,      // active-high clock enable / stall
    input  wire                 ap_start,   // ap_ctrl_chain: caller holds high until ap_ready
    input  wire                 ap_continue,// ap_ctrl_chain: caller pulses to clear ap_done
    output wire                 ap_ready,   // ap_ctrl_chain: 1-cycle start-token consumption
    output wire                 ap_done,    // ap_ctrl_chain: held until ap_continue
    output wire                 ap_idle,    // ap_ctrl_chain: no invocation in flight/pending

    // activation FIFO (input)  {abits} = ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{abits - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // output FIFO (output)     {pb_total} = N_TILES * ceil(PE*ACCU_WIDTH/8)*8
    output wire [{pb_total - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;

    // ---- ap_ctrl_chain invocation-level FSM: IDLE <-> RUN, one node/invocation ----
    localparam IDLE = 1'd0, RUN = 1'd1;
    reg                        state = IDLE;
    reg                        done_r = 0;
    reg  [{_w(in_total + 1) - 1}:0]  icnt = 0;   // activation beats accepted this node
    reg  [{_w(run_total + 1) - 1}:0]  ocnt = 0;   // output beats produced this node

    assign ap_ready = (state == IDLE) & ~done_r & ap_start & ap_ce;
    assign ap_done  = done_r;
    assign ap_idle  = (state == IDLE) & ~done_r;

    always @(posedge ap_clk) begin
        if (ap_rst) begin
            state <= IDLE; done_r <= 0; icnt <= 0; ocnt <= 0;
        end else if (ap_ce) begin
            if (ap_ready) begin
                state <= RUN; icnt <= 0; ocnt <= 0;
            end else if (state == RUN) begin
                if (in_tvalid & (&in_tready)) icnt <= icnt + 1'b1;
                if (p_write) begin
                    if (ocnt == {run_total - 1}) begin
                        state <= IDLE; done_r <= 1'b1;
                    end else ocnt <= ocnt + 1'b1;
                end
            end
            if (done_r & ap_continue) done_r <= 1'b0;
        end
    end

    // gate on icnt too: stop pulling A beats once this node's {in_total} beats
    // are accepted, even if the next node's rows are already queued in the FIFO.
    wire in_open = (state == RUN) & (icnt != {in_total});

    // shared activation valid + output ready, broadcast to every tile
    wire in_tvalid  = ap_ce & in_open & a_empty_n;
    wire out_tready = ap_ce & p_full_n;
    // per-tile handshakes: advance the activation FIFO only when all tiles accept,
    // emit a beat only when all tiles have produced theirs (tiles run in lockstep).
    wire [{n_tiles - 1}:0] in_tready;
    wire [{n_tiles - 1}:0] out_tvalid;
    assign a_read  = ap_ce & in_open & (&in_tready);
    assign p_write = ap_ce & (&out_tvalid) & p_full_n;   // count only real transfers

{blocks}endmodule
"""
