"""mvau RTL emission: the thin shim around FINN's ``mvu_vvu_axi``.

Generalizes the cosim-validated ``temp_space/mvau-spike/mvau_bb.v``. One shim =
one MVU tile: it instantiates ``mvu_vvu_axi`` with the tile's folding parameters
and adapts the FINN AXIS interface to the Vitis-HLS RTL-blackbox contract:

  * active-high ``ap_rst``  ->  FINN's active-low ``ap_rst_n`` (inverted)
  * ``ap_ce`` global stall gating the three handshakes (safe on a fully
    backpressured module: no beat transfers when ce=0, dsp_zero injects bubbles)
  * ap_fifo ports the JSON binds (``*_dout/*_empty_n/*_read``, ``*_din/*_full_n/*_write``)
    -- AXIS ``TVALID/TREADY`` bind directly to ap_fifo ``empty_n/read`` & ``full_n/write``

The module name MUST equal the JSON ``c_function_name`` -- Vitis instantiates the
blackbox by the C function name, not ``rtl_top_module_name`` (learned in cosim).

Self-contained (only ``geometry`` as a sibling import).
"""

import geometry as _geom


def _tile(shape, tile=None, **plan_kwargs):
    """Return the per-instance MVU tile params for *shape*, computing the plan
    if a precomputed *tile* dict is not supplied."""
    if tile is not None:
        return tile
    return _geom.fold_plan(*shape, **plan_kwargs)["tile"]


def generate_shim(shape, module_name="mvau_core", force_behavioral=True,
                  tile=None, **plan_kwargs):
    """Emit the shim Verilog wrapping ``mvu_vvu_axi`` for one MVU tile.

    ``module_name`` must match the blackbox C function name. ``force_behavioral``
    bakes ``FORCE_BEHAVIORAL`` into the instance (1 for unisim-free cosim, 0 for
    real DSP primitives downstream).
    """
    t = _tile(shape, tile=tile, **plan_kwargs)
    wbits = t["weight_stream_width_ba"]
    abits = t["input_stream_width_ba"]
    pbits = t["output_stream_width_ba"]
    fb = 1 if force_behavioral else 0

    return f"""// Generated by gemm-ip-gen (mvau target). Shim around FINN's mvu_vvu_axi.
// Tile: MW(K)={t['mw']} MH(N)={t['mh']} PE={t['pe']} SIMD={t['simd']} \
core={t['compute_core']} ACCU={t['accu_width']}
// Module name MUST equal the JSON c_function_name (Vitis instantiates by it).
module {module_name} (
    input  wire                 ap_clk,
    input  wire                 ap_rst,     // active-high
    input  wire                 ap_ce,      // active-high clock enable / stall

    // weight FIFO (input)    {wbits} = ceil(PE*SIMD*WEIGHT_WIDTH/8)*8
    input  wire [{wbits - 1}:0] w_dout,
    input  wire                 w_empty_n,
    output wire                 w_read,
    // activation FIFO (input)  {abits} = ceil(SIMD*ACTIVATION_WIDTH/8)*8
    input  wire [{abits - 1}:0] a_dout,
    input  wire                 a_empty_n,
    output wire                 a_read,
    // output FIFO (output)     {pbits} = ceil(PE*ACCU_WIDTH/8)*8
    output wire [{pbits - 1}:0] p_din,
    input  wire                 p_full_n,
    output wire                 p_write
);
    wire rst_n = ~ap_rst;

    wire         wgt_tvalid, wgt_tready;
    wire         in_tvalid,  in_tready;
    wire         out_tvalid, out_tready;
    wire [{pbits - 1}:0] out_tdata;

    // ce-gated ap_fifo <-> AXIS binding (empty_n==TVALID, read==TREADY,
    //                                    full_n==TREADY, write==TVALID)
    assign wgt_tvalid = ap_ce & w_empty_n;
    assign w_read     = ap_ce & wgt_tready;
    assign in_tvalid  = ap_ce & a_empty_n;
    assign a_read     = ap_ce & in_tready;
    assign out_tready = ap_ce & p_full_n;
    assign p_write    = ap_ce & out_tvalid;
    assign p_din      = out_tdata;

    mvu_vvu_axi #(
        .IS_MVU({t['is_mvu']}),
        .COMPUTE_CORE("{t['compute_core']}"),
        .MW({t['mw']}), .MH({t['mh']}), .PE({t['pe']}), .SIMD({t['simd']}),
        .ACTIVATION_WIDTH({t['activation_width']}), .WEIGHT_WIDTH({t['weight_width']}),
        .ACCU_WIDTH({t['accu_width']}),
        .NARROW_WEIGHTS({t['narrow_weights']}), .SIGNED_ACTIVATIONS({t['signed_activations']}),
        .SEGMENTLEN({t['segmentlen']}), .PUMPED_COMPUTE(0), .FORCE_BEHAVIORAL({fb})
    ) inst (
        .ap_clk(ap_clk),
        .ap_clk2x(1'b0),
        .ap_rst_n(rst_n),
        .s_axis_weights_tdata(w_dout),
        .s_axis_weights_tvalid(wgt_tvalid),
        .s_axis_weights_tready(wgt_tready),
        .s_axis_input_tdata(a_dout),
        .s_axis_input_tvalid(in_tvalid),
        .s_axis_input_tready(in_tready),
        .m_axis_output_tdata(out_tdata),
        .m_axis_output_tvalid(out_tvalid),
        .m_axis_output_tready(out_tready)
    );
endmodule
"""
