"""Self-checking SystemVerilog testbench generator for the mvau RTL wrapper,
driven with real xvlog/xelab/xsim (see run_rtl_tests.py).

Unlike golden.py (which emits a C++ TB for Vitis HLS csim/cosim), this module
drives the *raw shim* Verilog (rtl.generate_shim / generate_two_operand_shim)
directly at the RTL level with a hand-written SV TB, exactly the way
tensor_slice/golden.py drives its combined core with an iverilog TB. The two
port "shapes" actually emitted (see rtl.py, confirmed by reading generated .v
output under temp_space/mvau-ws and the mvu_vvu_axi shim sources):

  ws       -- weight-stationary: ap_ctrl_chain + a_dout/a_empty_n/a_read +
              p_din/p_full_n/p_write. One raw K-wide beat in, one raw N-wide
              beat out, per vector. No weight port (baked memstream).
  2op      -- two-operand, single-tile (``dynamic_load_2op``, any depth incl.
              the fully-spatial DEPTH==1 case): same ap_ctrl_chain + a_*/p_*
              as ws, PLUS b_dout/b_empty_n/b_read. B is the loader's own
              narrow beat (PE-wide Mode A / SIMD-wide Mode B), A is SF
              beats/vector of byte-aligned SIMD*AW bits, P is NF beats/vector
              of byte-aligned PE*out_width bits (SF==NF==1 -> one beat each).

Stimulus/expected values reuse the exact deterministic generators golden.py's
C-twin testbenches use (``_ws_tb``/``_2op_tb`` in golden.py): same seeded
formulas for X and (for two-operand) B, same round-half-up/wrap requant
reference -- just re-evaluated here in Python instead of emitted as C++, so
the RTL-level SV TB and the HLS-level C++ TB check the same numbers.
Weight-stationary baked weights reuse ``package._synth_weights`` (the same
deterministic weight matrix ``generate_mvau_pkg`` bakes when no real weights
are supplied).
"""
from pathlib import Path


# ── deterministic reference generators (mirrors golden.py's C-twin formulas) ──

def synth_weights(n, k, ww, seed=42):
    """Same deterministic [K][N] weight matrix as package._synth_weights."""
    wrange = (1 << (ww - 1)) - 1
    wmod = min(7, 2 * wrange + 1)
    off = wrange if wmod == 2 * wrange + 1 else 3
    return [[((oo + kk + seed) % wmod) - off for oo in range(n)] for kk in range(k)]


def _act_range(aw, signed):
    arange = (1 << (aw - 1)) - 1 if signed else (1 << aw) - 1
    amod = min(7, arange + 1)
    aoff = 3 if signed else 0
    return amod, aoff


def synth_activations(m, k, aw, signed, seed, node=0):
    """Same deterministic X[v][k] formula as golden.py's _ws_tb/_2op_*_tb."""
    amod, aoff = _act_range(aw, signed)
    return [[((v * 2 + kk + 3 * node + seed) % amod) - aoff for kk in range(k)]
            for v in range(m)]


def synth_b_stream(k, n, ww, seed, node=0):
    """Same deterministic Bm[k][o] formula as golden.py's _2op_tb."""
    wrange = (1 << (ww - 1)) - 1
    wmod = min(7, 2 * wrange + 1)
    off = wrange if wmod == 2 * wrange + 1 else 3
    return [[((oo + kk + 5 * node + seed) % wmod) - off for oo in range(n)]
            for kk in range(k)]


def requant_ref(acc, shift, out_width):
    if shift > 0:
        q = (acc + (1 << (shift - 1))) >> shift
    elif shift < 0:
        q = acc << (-shift)
    else:
        q = acc
    mask = (1 << out_width) - 1
    q &= mask
    if q & (1 << (out_width - 1)):
        q -= (1 << out_width)
    return q


def _u2(val, width):
    """Two's-complement code for a signed int, masked to width bits."""
    return val & ((1 << width) - 1)


def pack_beat(values, width):
    """Pack a list of signed ints (lane 0 in LSBs), width bits each, into one int."""
    word = 0
    for i, v in enumerate(values):
        word |= _u2(v, width) << (i * width)
    return word


def write_dat(path, words, hex_digits):
    path.write_text("\n".join(format(w, "x").zfill(hex_digits) for w in words) + "\n")


# ── SV testbench template (generic across the three port shapes) ────────────

_HEADER = """\
`timescale 1ns/1ps
// Generated by gemm-ip-gen (mvau target) rtl_sv_tb.py -- self-checking RTL testbench.
module tb;
  localparam AW = {ab};
  localparam PW = {pb};
  localparam A_BEATS = {a_beats};   // total A beats over all nodes
  localparam P_BEATS = {p_beats};   // total P beats over all nodes
  localparam NNODES  = {n_nodes};
{bw_localparam}
  reg ap_clk = 0, ap_rst = 1;
  reg ap_ce = 1;
  reg ap_start = 0;
  wire ap_ready, ap_done, ap_idle;
  // ap_continue: ack a pending completion the instant ap_done is seen -- legal
  // under ap_ctrl_chain (the caller may assert ap_continue any cycle ap_done is
  // high) and lets a run of several already-pending done_pending completions
  // drain one per cycle without a separate driver process.
  wire ap_continue = ap_done;

  reg  [AW-1:0] a_dout;
  reg           a_empty_n = 0;
  wire          a_read;
{b_ports_decl}
  wire [PW-1:0] p_din;
  reg           p_full_n = 0;
  wire          p_write;

  reg [AW-1:0] a_mem [0:A_BEATS-1];
  reg [PW-1:0] exp_mem [0:P_BEATS-1];
{b_mem_decl}

  integer a_idx = 0, p_idx = 0, p_raw = 0;
  integer n_match = 0, n_mismatch = 0;
{b_idx_decl}

  // ---- free-running cycle counter (for latency measurement) ----
  integer cyc = 0;
  always @(posedge ap_clk) begin
    if (ap_rst) cyc <= 0;
    else cyc <= cyc + 1;
  end

  initial begin
    $readmemh("{a_dat}", a_mem);
    $readmemh("{exp_dat}", exp_mem);
{b_readmemh}
  end

  always #2.5 ap_clk = ~ap_clk;   // 5 ns period

  {dut_inst}

  // ---- reset ----
  initial begin
    ap_rst = 1;
    repeat (10) @(posedge ap_clk);
    ap_rst = 0;
  end

  // ---- randomized backpressure: gap A / stall P ----
  reg [31:0] lfsr = 32'hACE1DEAD;
  function automatic bit rnd_bit;
    lfsr = {{lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]}};
    rnd_bit = lfsr[0];
  endfunction

{a_empty_process}

{p_full_process}

{b_feed_process}

{fsm_debug_process}

  // ---- feed A ----
  // NOTE: a_read/a_empty_n are sampled combinationally against the CURRENT
  // a_dout, so the beat consumed this edge is a_mem[a_idx] (pre-increment).
  // a_dout must therefore be advanced to the NEXT beat, a_mem[a_idx+1], not
  // re-loaded with a_mem[a_idx] -- otherwise a run of back-to-back consumed
  // beats (no empty/backpressure gap between them) presents the same beat
  // twice and silently drops the last beat of that run.
  always @(posedge ap_clk) begin
    if (!ap_rst && a_read && a_empty_n) begin
      if (a_idx + 1 < A_BEATS) a_dout <= a_mem[a_idx + 1];
      a_idx <= a_idx + 1;
    end
  end
  initial a_dout = a_mem[0];

  // ---- drain + check P ----
  always @(posedge ap_clk) begin
    if (!ap_rst && p_write && p_full_n) begin
      if (p_din === exp_mem[p_idx]) n_match = n_match + 1;
      else begin
        n_mismatch = n_mismatch + 1;
        $display("MISMATCH beat=%0d got=%h exp=%h", p_idx, p_din, exp_mem[p_idx]);
      end
      p_idx = p_idx + 1;
      p_raw = p_raw + 1;
    end
  end

  // ---- top-level: pipelined driver ----
  // ap_start is held high for as long as nodes remain (the dataflow-region
  // contract the decoupled handshake relies on) instead of being dropped and
  // re-raised per node; a node's ap_ready pulse is consumed the same cycle it
  // fires (ap_ready is a combinational pulse, so no waiting is needed once
  // ap_start is up). A separate always block acks ap_done as soon as it's
  // seen (see the ap_continue assign above) and stamps each node's done cycle
  // -- decoupled from the ready stamps below, since with pipelining a node's
  // ap_done can land many cycles after (or, with enough MAX_INFLIGHT headroom,
  // even before) the NEXT node's ap_ready.
  integer ready_count = 0, done_count = 0;
  integer ready_cyc_arr [0:NNODES-1];
  integer done_cyc_arr  [0:NNODES-1];
  integer first_start_cyc = 0, last_done_cyc = 0;
  real per_node_cyc;

  initial begin
    ap_start = 0;
    @(negedge ap_rst);
    repeat (3) @(posedge ap_clk);
    @(posedge ap_clk); #1;
    first_start_cyc = cyc;
    ap_start = 1;   // held high until all NNODES nodes have been accepted
  end

  always @(posedge ap_clk) begin
    if (!ap_rst && ap_start && ap_ready && ready_count < NNODES) begin
      ready_cyc_arr[ready_count] = cyc;
      $display("NODE %0d ready=%0d", ready_count, cyc);
      ready_count = ready_count + 1;
      if (ready_count == NNODES) ap_start <= 1'b0;
    end
  end

  always @(posedge ap_clk) begin
    if (!ap_rst && ap_done && done_count < NNODES) begin
      done_cyc_arr[done_count] = cyc;
      last_done_cyc = cyc;
      $display("NODE %0d done=%0d", done_count, cyc);
      done_count = done_count + 1;
    end
  end

  initial begin
    wait (done_count == NNODES);
    per_node_cyc = (last_done_cyc - first_start_cyc) * 1.0 / NNODES;
    $display("CYCLES nodes=%0d first_start=%0d last_done=%0d per_node=%0.3f",
              NNODES, first_start_cyc, last_done_cyc, per_node_cyc);
    // drain any remaining output beats
    begin : drain_wait
      integer dc;
      for (dc = 0; dc < 20000; dc = dc + 1) begin
        @(posedge ap_clk);
        if (p_raw >= P_BEATS) disable drain_wait;
      end
    end

    if (n_mismatch == 0 && p_idx == P_BEATS)
      $display("TEST_RESULT: PASS n_match=%0d n_mismatch=%0d total=%0d", n_match, n_mismatch, P_BEATS);
    else
      $display("TEST_RESULT: FAIL n_match=%0d n_mismatch=%0d total=%0d (got %0d beats, expected %0d)",
                n_match, n_mismatch, P_BEATS, p_idx, P_BEATS);
    $finish;
  end
endmodule
"""


def generate_sv_tb(kind, module_name, ab, pb, a_beats, p_beats, n_nodes,
                   a_dat, exp_dat, bb=None, b_beats=None, b_dat=None,
                   backpressure=True, fsm_debug=False, sustained_output_stall=False):
    """Build the SV TB text. ``kind`` is 'ws' (no B port) or '2op' (has B port).

    ``backpressure`` (default True, unchanged behaviour): random a_empty_n /
    b_empty_n gaps and random p_full_n stalls, biased toward valid/ready.
    When False, a_empty_n/b_empty_n/p_full_n are asserted every cycle data
    remains (no artificial stalling), so measured cycles reflect only the
    wrapper/core's own pipeline cost.

    ``sustained_output_stall`` keeps A (and B, if present) flowing and stalls
    P for eight cycles immediately after its first produced beat.  It is a
    deterministic output-queue stress schedule, used for the SF=1 regression.

    ``fsm_debug`` (2op only): emit extra $display stamps -- FSM_WRITE/FSM_RUN
    (cycle the DUT's internal ``state`` register enters WRITE/RUN, via the
    hierarchical ``dut.state`` reference -- only meaningful for the memstream
    ('ms') two-operand shim, which has the IDLE/FILL/WRITE/DRAIN/RUN FSM),
    A_BEAT (cycle each A beat is accepted) and P_BEAT (cycle each P beat is
    written).
    """
    if sustained_output_stall:
        a_empty_process = """
  // Keep the core fed while the output queue is deliberately stalled.
  always @(posedge ap_clk) begin
    if (ap_rst) a_empty_n <= 0;
    else a_empty_n <= (a_idx < A_BEATS);
  end"""
        p_full_process = """
  // After one accepted result, block eight output cycles.  An SF=1 core emits
  // each cycle here, which must fit its pipeline drain without queue overflow.
  integer oq_stall_cycles = 0;
  reg oq_stall_started = 0;
  always @(posedge ap_clk) begin
    if (ap_rst) begin
      p_full_n <= 0;
      oq_stall_cycles <= 0;
      oq_stall_started <= 0;
    end else if (!oq_stall_started) begin
      p_full_n <= 1'b1;
      if (p_write) oq_stall_started <= 1'b1;
    end else if (oq_stall_cycles < 8) begin
      p_full_n <= 1'b0;
      oq_stall_cycles <= oq_stall_cycles + 1;
    end else begin
      p_full_n <= 1'b1;
    end
  end"""
    elif backpressure:
        a_empty_process = """\
  always @(posedge ap_clk) begin
    if (ap_rst) a_empty_n <= 0;
    else if (!a_empty_n || (a_read && a_empty_n)) begin
      // present a new beat only if data remains; randomized gap otherwise
      if (a_idx < A_BEATS) a_empty_n <= rnd_bit() | rnd_bit();  // biased toward valid
      else a_empty_n <= 0;
    end
  end"""
        p_full_process = """\
  always @(posedge ap_clk) begin
    if (ap_rst) p_full_n <= 0;
    else p_full_n <= rnd_bit() | rnd_bit() | rnd_bit();  // biased toward ready
  end"""
    else:
        a_empty_process = """\
  // backpressure disabled: present a beat every cycle data remains
  always @(posedge ap_clk) begin
    if (ap_rst) a_empty_n <= 0;
    else a_empty_n <= (a_idx < A_BEATS);
  end"""
        p_full_process = """\
  // backpressure disabled: always ready to accept an output beat
  always @(posedge ap_clk) begin
    if (ap_rst) p_full_n <= 0;
    else p_full_n <= 1'b1;
  end"""

    fsm_debug_process = ""
    if fsm_debug and kind != "ws":
        # NOTE: the two-operand ("ms") shim no longer has an IDLE/FILL/WRITE/DRAIN/RUN
        # state register (dynamic_load_2op replaces that FSM) -- only a run_r/done_r
        # pair. FSM_WRITE (there is no WRITE phase to load B into anymore; B streams
        # into the loader independently of ap_ctrl) is dropped; FSM_RUN stamps
        # run_r's rising edge instead of a state-register transition.
        fsm_debug_process = """\
  // ---- fsm_debug: extra latency-breakdown stamps ----
  reg dbg_prev_run = 1'b0;
  always @(posedge ap_clk) begin
    if (ap_rst) dbg_prev_run <= 1'b0;
    else begin
      if (dut.run_r && !dbg_prev_run) $display("FSM_RUN cyc=%0d", cyc);
      dbg_prev_run <= dut.run_r;
    end
  end
  always @(posedge ap_clk)
    if (!ap_rst && a_read && a_empty_n) $display("A_BEAT cyc=%0d", cyc);
  always @(posedge ap_clk)
    if (!ap_rst && p_write && p_full_n) $display("P_BEAT cyc=%0d", cyc);"""

    if kind == "ws":
        b_ports_decl = ""
        b_mem_decl = ""
        b_idx_decl = ""
        b_readmemh = ""
        b_feed_process = ""
        bw_localparam = ""
        dut_inst = (f"{module_name} dut (.ap_clk(ap_clk), .ap_rst(ap_rst), .ap_ce(ap_ce), "
                    ".ap_start(ap_start), .ap_continue(ap_continue), "
                    ".ap_ready(ap_ready), .ap_done(ap_done), .ap_idle(ap_idle), "
                    ".a_dout(a_dout), .a_empty_n(a_empty_n), .a_read(a_read), "
                    ".p_din(p_din), .p_full_n(p_full_n), .p_write(p_write));")
    else:
        bw_localparam = f"  localparam BW = {bb};\n  localparam B_BEATS = {b_beats};"
        b_ports_decl = ("  reg  [BW-1:0] b_dout;\n"
                        "  reg           b_empty_n = 0;\n"
                        "  wire          b_read;\n")
        b_mem_decl = "  reg [BW-1:0] b_mem [0:B_BEATS-1];\n"
        b_idx_decl = "  integer b_idx = 0;\n"
        b_readmemh = f'    $readmemh("{b_dat}", b_mem);\n'
        if backpressure:
            b_empty_process = """\
  always @(posedge ap_clk) begin
    if (ap_rst) b_empty_n <= 0;
    else if (!b_empty_n || (b_read && b_empty_n)) begin
      // mirror the A-side hold logic: once asserted, b_empty_n/b_dout must
      // stay stable until the DUT actually consumes the beat (b_read fires).
      // Re-randomizing every cycle regardless of consumption (as this used
      // to do) glitches a held-valid beat low before it's read, violating
      // the valid/ready stability the DUT's B-side FSM relies on and
      // causing spurious re-presentation of beats -- a second misalignment
      if (b_idx < B_BEATS) b_empty_n <= rnd_bit() | rnd_bit();
      else b_empty_n <= 0;
    end
  end"""
        else:
            b_empty_process = """\
  // backpressure disabled: present a beat every cycle data remains
  always @(posedge ap_clk) begin
    if (ap_rst) b_empty_n <= 0;
    else b_empty_n <= (b_idx < B_BEATS);
  end"""
        b_feed_process = f"""
{b_empty_process}
  always @(posedge ap_clk) begin
    if (!ap_rst && b_read && b_empty_n) begin
      if (b_idx + 1 < B_BEATS) b_dout <= b_mem[b_idx + 1];
      b_idx <= b_idx + 1;
    end
  end
  initial b_dout = b_mem[0];
"""
        dut_inst = (f"{module_name} dut (.ap_clk(ap_clk), .ap_rst(ap_rst), .ap_ce(ap_ce), "
                    ".ap_start(ap_start), .ap_continue(ap_continue), "
                    ".ap_ready(ap_ready), .ap_done(ap_done), .ap_idle(ap_idle), "
                    ".a_dout(a_dout), .a_empty_n(a_empty_n), .a_read(a_read), "
                    ".b_dout(b_dout), .b_empty_n(b_empty_n), .b_read(b_read), "
                    ".p_din(p_din), .p_full_n(p_full_n), .p_write(p_write));")

    return _HEADER.format(
        ab=ab, pb=pb, a_beats=a_beats, p_beats=p_beats, n_nodes=n_nodes,
        bw_localparam=bw_localparam, b_ports_decl=b_ports_decl,
        b_mem_decl=b_mem_decl, b_idx_decl=b_idx_decl, b_readmemh=b_readmemh,
        b_feed_process=b_feed_process, a_dat=a_dat, exp_dat=exp_dat,
        dut_inst=dut_inst, a_empty_process=a_empty_process,
        p_full_process=p_full_process, fsm_debug_process=fsm_debug_process,
    )
